elf2cfetbl.c
Fix #2, fix mismatch in printf. Used cppcheck with options --enable=performance,portability,warning --std=c99 --std=posix --inconclusive -j 8
1. Run cppcheck with options --enable=performance,portability,warning --std=c99 --std=posix --inconclusive -j 8
2. Verify warning is gone
3. Build
4. Verify elf2cfetbl still compile and pass table.o through
No impact to behavior
**System(s) tested on:**
- Hardware
- Ubuntu 18.04
- cFE 6.7.0
**Contributor Info**
Anh Van, NASA Goddard
**Community contributors**
You must attach a signed CLA (required for acceptance) or reference one already submitted
=> Fix #2, fix long string mismatch

CMakeLists.txt, Guide-Creating-Table-files.txt, elf2cfetbl.c
Integration candidate for pull requests approved at 2019-10-09 CCB
Covers the following pull requests:
#15 - Add guide on creating table files
#20 - add validation for rtncode and update bracket to standard
#21 - init DstFile and SrcFile to NULL, Validate DstFile and SrcFile
#23 - use path_max instead of os_max_file_name
#24 - Clean up elf2cfetbl build logic
Build code for native host (SIMULATION=native) with unit test enabled
Execute CFE core, issued various test commands from cmdUtil
Execute all unit tests and confirm passage.
None
**System(s) tested on:**
Ubuntu 18.04.2 LTS 64-bit
NA
**Contributor Info**
Joseph Hickey, Vantage Systems, Inc.
=> Integration candidate 2019-10-09

CMakeLists.txt, elf2cfetbl.c
Remove the now-unnecessary inclusion of CFE TBL internal definitions.
All logic in this tool is based on public include files only.
CFE ensures that the header sizes are always a multiple of 4 bytes,
so the logic to selectively byte-align is unnecessary.  CFE now
requires this to be 4-byte aligned.
Clean up all hacks in the CMake recipe, the build is now much
more straightforward when internal headers aren't being used.
Fixes issue #22, cleans up the build process for this tool.
_IMPORTANT_ - This depends on nasa/cfe#27 and cannot be merged/tested prior to this being merged.  This can only be cleaned up on this side once it is ensured that the internal CFE_TBL definitions are no longer required here.
Note this also removes the `-n` option to the tool, as …
=> Fix #22: Clean up elf2cfetbl build logic

elf2cfetbl.c
Fix #5, used path_max instead of os_max_file_name. 
Steps taken to test the contribution:
1. Build 
2. Create sample_table.tbl file using elf2cfetbl. Used full path to trigger warning:
3. Verify warning and that tbl file is still created. 
```
Lenght of Source Filename + Path exceed OS_MAX_FILE_NAME
Lenght of Destination Filename + Path exceed OS_MAX_FILE_NAME
```
4. Used sample_table.tbl file and verify it still work in cFS. 
**System(s) tested on:**
- Hardware
- 18.04.03
- cFE 6.7.0, elf2cfetbl 3.1.1
**Contributor Info**
Anh Van, NASA Goddard
**Community contributors**
You must attach a signed CLA (required for acceptance) or reference one already submitted
=> Fix #5, use path_max instead of os_max_file_name

elf2cfetbl.c
Fix #17. Resolve warning with flags  -Wall -std=c99 -pedantic -Wstrict-prototypes -Wwrite-strings
Steps taken to test the contribution:
1. Build 
2. Verify warning does not appear
3. Execute elf2cfetbl against table object
4. Verify *.tbl is generated
5. Execute again with DDD
6. Force RtnCode = -1
7. Verify *.tbl is generated
No impact to behavior
**System(s) tested on:**
- Hardware
- Ubuntu 18.04.03
- elf2cfetbl version 3.1.0, cFE 6.7.0
**Contributor Info**
Anh Van, NASA Goddard
**Community contributors**
You must attach a signed CLA (required for acceptance) or reference one already submitted
=> Fix #17, add validation for rtncode and update bracket to standard

elf2cfetbl.c
Casts where needed for print formatting on 32-bit host
Fix #33
Steps taken to test the contribution:
1. CI - See https://travis-ci.com/github/skliper/cFS/builds/160575856
2. Also built for vxworks on 32-bit host
Builds for vxworks w/ 32-bit host
- Hardware: CI, cross compiled for VxWorks 6.9 MCP750 on 32-bit linux host
- OS: Ubuntu 18.04, VxWorks 6.9, Redhat 6.10
- Versions: Bundle + this commit
None (this isn't the only issue on vxworks, but haven't written them up yet)
None
=> Fix #33, Resolve print format mismatches on 32-bit host

README.md, elf2cfetbl.c
Fixes #33 
See PR
Bundle CI - 
PR #36 -  Builds for vxworks w/ 32-bit host
See PRs
Bundle CI - Ubuntu:Bionic
Part of https://github.com/nasa/cFS/pull/74
Jacob Hageman, NASA-GSFC
=> Integration Candidate: 2020-04-22

elf2cfetbl.c
Fix possible non-termination of strings within command line parsing.
This generated a warning in GCC9.
Fixes #37
Build code with default config, SIMULATION=native BUILDTYPE=release on GCC 9.3.0.
Confirm successful build with no warning.
No impact to behavior
Ubuntu 20.04 LTS 64 bit
Joseph Hickey, Vantage Systems, Inc.
=> Fix #37, termination on strncpy

ELF_Structures.h, README.md, README.txt, elf2cfetbl.c
Fixes #37
See PRs
Bundle CI - https://travis-ci.com/github/nasa/cFS/builds/165726730
PR #38 - No string termination warnings in GCC9.
PR #39 - Fix typos
See PRs
Bundle CI
Part of nasa/cfs#83
Joseph Hickey, Vantage Systems, Inc.
Pierre Grimaud, self
=> Integration Candidate COMBINED 2020-04-29 and 2020-05-06

elf2cfetbl.c
Adds a null to the end of SrcFilename and DstFilename when using strncpy.
Christopher.D.Knight@nasa.gov
=> Fix #45 - null terminates src/dst filenames

elf2cfetbl.c
Support ELF files that have all strings, including ELF section names, in one single ".strtab" section in the ELF file.
This gives preferential treatment to a section named ".strtab" as this should always be the section which contains the names for the ".symtab" section.
This should also be true of ELF files that contain other strtab sections, such as a ".dynstr" section.
Fixes #48
Confirmed that normal table files built using GCC (e.g. those in the sample framework configuration) are identical, before and after this change is applied.
Confirmed that this is now able to also correctly parse an ELF file from `clang` which has all strings in a single `.strtab` section.
Now correctly parses ELF files that do …
=> Fix #48, string table identification.

elf2cfetbl.c, elf2cfetbl_version.h
Resolve #6 
Resolve #50 
None yet
Version reporting now uses the version numbers defined in `elf_version.h`
If included, identify any third party code and provide text file of license
Gerardo E. Cruz-Ortiz, NASA-GSFC
=> Resolve #50, Add baseline and build number to version.h

README.md, elf2cfetbl.c, elf2cfetbl_version.h
Fix #45 
Fix #48 
Resolve #6
Resolve #50
Bundle CI - https://github.com/nasa/cFS/pull/108/checks
PR #46 -  Adds a null to the end of SrcFilename and DstFilename when using strncpy.
PR #49 - Support ELF files that have all strings, including ELF section names, in one single ".strtab" section in the ELF file.
PR #51 - Version reporting now uses the version numbers defined in `elf_version.h` and reports build number.
Ubuntu - CI
Part of https://github.com/nasa/cFS/pull/108
None
Christopher D. Knight, NASA-ARC
Joseph Hickey, Vantage Systems, Inc.
Gerardo E. …
=> Integration Candidate: 2020-06-24

elf2cfetbl.c
Fix #58 - replace ctime (which generates LGTM warning) with ctime_r
Built and ran code in verbose mode, confirmed time output
Eliminate LGTM warning
- Hardware: cFS Dev Server
- Versions: bundle main (+ cfe/osal main) + this change
None
None
=> Fix #58, Replace ctime with ctime_r

elf2cfetbl.c
Fix #56 - squash int comparison warning
Build and ran cfe (uses tables built by elf2cfetbl), no issues.
No longer produce the LGTM warning.  No behavior change.
- Hardware: cFS Dev Server
- Versions: bundle main (+ cfe/osal main) + this change.
None
None
=> Fix #56, Squash int comparison warning

elf2cfetbl.c
Fix #60 - deconflicts global/local parameters
Built and executed cFS, loaded tables as expected
None, squashed warning
- Hardware: cFS Dev Server
- Versions: bundle main (+ cfe/osal main) + this commit
None
None
=> Fix #60, Deconflict global and local parameters

elf2cfetbl.c
Fix #54 - restricts destination file permissions
Built and ran elf2cfetbl, confirmed file permissions restricted (checked w/ verbose)
Created file not writable by group or other.
- Hardware: cFS Dev Server
- Versions: bundle main + this commit
CWE-732
None
=> Fix #54, Restrict destination file permissions

README.md, elf2cfetbl.c, elf2cfetbl_version.h
Fix #54 
Fix #56 
Fix #58 
Fix #60 
Bundle CI - https://github.com/nasa/cFS/pull/134/checks
PR #55 - Restricts destination file permissions
PR #57 - Squash int comparison warning
PR #59 - Replace ctime (which generates LGTM warning) with ctime_r
PR #61 - Deconflicts global/local parameters
Ubuntu - CI
https://github.com/nasa/cFS/pull/134
Jacob Hageman, NASA-GSFC
=> Integration Candidate 2020-08-26

SECURITY.md
Fix #63 
Created a draft of a security policy markdown file for elf2cfetbl. The purpose of a security policy is to inform users on how to submit bugs or vulnerabilities. It is ideal to include a section for supported versions.
Optional sections that may be included:
- What to expect security-wise such as what type of testing is done
- Address privacy concerns
- Supported versions
- License
- Known vulnerabilities
References to Public Security Policies:
https://github.com/thanos-io/thanos/security/policy
https://github.com/minhealthnz/nzcovidtracer-app/security/policy
https://github.com/odoo/odoo/security/policy
Ariel Adams, ASRC Federal
=> Fix #63, Create Security Policy

.github/workflows/codeql-build.yml
Fix #68 - adds CodeQL analysis
Differences from bundle - just builds elf2cfetbl, has timeout
Ran on fork
Adds Code QL analysis on push to main and pull requests (to main)
CI
None
None
=> Fix #68, Add CodeQL analysis to workflow

README.md, elf2cfetbl.c, elf2cfetbl_version.h
Fix #70, fix comment stlye
See <https://github.com/nasa/cFS/pull/204/checks>
PR #71 - Changes cpp-styled comments to c-style to meet coding standard
Ubuntu 18.04
Part of <https://github.com/nasa/cFS/pull/204/>
None
@zanzaben
=> elf2cfetbl Integration candidate: 2021-03-02

SECURITY.md
Fix #73
Updated the Security Policy to include the type of testing done for elf2cfetbl under a new section titled "Testing". Provided a disclaimer that under the Apache license, liability is not provided. 
Added that security reports should be emailed. 
Users should now be aware of the type of testing elf2cfetbl  undergoes. 
References: 
https://github.com/thanos-io/thanos/security/policy
https://github.com/phpMussel/phpMussel/security/policy
https://github.com/timberio/vector/security/policy
Ariel Adams, ASRC Federal
=> Fix #73, Add Testing Tools to the Security Policy

CONTRIBUTING.md
Fix #76 
Added a contributing guide that links to the main cFS contributing guide. 
Users should be able to view the contributing guide contents easily from the elf2cfetbl repo. 
Ariel Adams, ASRC Federal
=> Fix #76, Add Contributing Guide

.github/workflows/codeql-build.yml
Fix #78
Added the duplicate jobs action to avoid duplicate jobs from running. Added a separate job for coding standard queries. Created two configuration files, one for default queries and security queries and another for jpl rules. Removed push on main branch so when users push code to their forked repos, the workflow runs. Added main branch to pull request, so CodeQL runs on pull request made in the main branch. This is the same logic used in the cFS bundle repo. 
Testing done on cFE forked repository, ArielSAdamsNASA/cFE which used the same files, but with different configuration paths.
Jobs were failing when the entire path of the configuration file were not used. Have to use nasa/cFE/.github/codeql/config-name@branch-name. The …
=> Fix #78, Implement Coding Standard CodeQL

Guide-Creating-Table-files.txt, README.txt, SECURITY.md, elf2cfetbl.c, elf2cfetbl_version.h
Fixed various minor text typos in comments and event message strings.
Only automated checks.
None (minor comments and event message strings that do not interact with any max lengths etc.). Code execution is unaffected.
n/a
n/a
**Code contributions**
n/a
=> Fixed comment and event message typos.

elf2cfetbl_version.h
- Fix #101 
Make doc, observe no filename warnings
None
- Hardware: i5/wsl
- Versions: Bundle main + this commit
None
None
=> Fix #101, Remove explicit filename doxygen comments
